drm/msm: use __s32, __s64, __u32 and __u64 from linux/types.h for uabi
Fixes userspace compilation errors like:

error: unknown type name ‘uint32_t’

Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>
Signed-off-by: Rob Clark <robdclark@gmail.com>

(cherry picked from commit 6747b42)
Signed-off-by: hexc0de <tsehcode@gmail.com>

Change-Id: I1c99787cd050ad0d2accc206494320d66004b915